# https://taskfile.dev

version: '3'

vars:
  GREETING: 

tasks:

  prepare:
    deps: [build]
    summary: |
      Release your project to github

      It will build your project before starting the release.
      Please make sure that you have set GITHUB_TOKEN before starting.
    cmds:
      - npx @biomejs/biome format --write ./src/*
      - npx @biomejs/biome lint --max-diagnostics none --write ./src/*
      
  build:
    cmds:
      - npm install
      - npm run build

  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
